name: build

on:
  push:
    branches: [main, tee-tls]
  pull_request:
    branches: [main, tee-tls]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current project
        uses: actions/checkout@v3

      - name: Clone tlsn-js repository
        run: |
          git clone --branch tee-tls https://github.com/EternisAI/tlsn-js.git ../tlsn-js

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          cd ../tlsn-js && npm install && cd -

      - name: Build tlsn-js
        run: cd ../tlsn-js && npm run build && cd -

      - name: Build current project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./build
