name: build

on:
  push:
    branches: [main, tee-tls]
  pull_request:
    branches: [main, tee-tls]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current project
        uses: actions/checkout@v3

      - name: Checkout tlsn-js
        uses: actions/checkout@v3
        with:
          repository: eternisai/tlsn-js
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ../tlsn-js
          ref: tee-tls

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd ../tlsn-js && npm install && cd -
          npm install

      - name: Build tlsn-js
        run: cd ../tlsn-js && npm run build && cd -

      - name: Build current project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./build
